### ISSUE TITLE
Add Bridge to client template

### ISSUE THREAD

**Issue by tko22** [hack4impact-uiuc/mern-template#5]
This looks cool! I like use of `errorWrap`.

 Can we add bridge to the client template as part of the downloadable package? That way we link our h4i packages together

**Comment by n3a9** [comment]
I think that the template should provide as little as possible and just act as a starting point where anyone can add their own additional component library or styling.

A couple things with bridges:
1) No live development for Bridge
2) Accessibility standards
3) Lack of styling of components (may not conform to nonprofit branding)

Currently Bridge is mentioned in Hack4Impact UIUC packages in the Notion, where leads can decide if they want to use it there.
